"""Generate robogauge's A2 robot MJCF from the LOCKED sensorized A2 body — programmatically.

Part of WP2(b) of the Point Motion EVAL PREP workstream. The robogauge MuJoCo simulator
(`tasks/simulator/mujoco_simulator.py`) expects a robot XML with a very specific shape:
  - a body named `base_link` carrying a `<freejoint>` (the sim removes it and re-adds `root`),
  - 12 hinge joints `FL/FR/RL/RR_{hip,thigh,calf}_joint`,
  - an `imu` site,
  - 12 `<motor>` actuators in joint order,
  - per-joint `jointpos`/`jointvel`/`jointactuatorfrc` sensors,
  - IMU sensors `framequat`/`gyro`/`accelerometer`/`framepos`/`framelinvel` on the imu site,
  - foot geoms/sites named FL/FR/RL/RR (used by the friction/zmp metrics).

The Point Motion A2 SENSORIZED body (`a2_sensorized.xml`, generated by
`tools/gear_sonic_fk/a2_sensorized_mjcf.py`, LOCKED 2026-06-10) already has the body tree, the
12 joints, the `imu` site, and the FL/FR/RL/RR foot sites — but NO actuators and only the
mjlab sensor set. This tool reads that body and ADDS the robogauge actuator + sensor blocks,
PROGRAMMATICALLY (never hand-typed): it copies the worldbody verbatim and synthesizes the
actuator/sensor elements from the joint list it discovers in the body. The meshes are copied
into `assets/` and the `meshdir` is rewritten so the result is self-contained (mesh-free
fallback: pass --no-meshes to strip visual meshes for headless CI where STLs are absent).

This keeps the A2 body IDENTICAL to the training/eval body (same masses, inertias, collision,
the OS0 payload) — the only thing this tool authors is the actuator/sensor plumbing robogauge
needs, derived from the body, not transcribed by hand.

USAGE
  python3 make_a2_robot_xml.py --src /path/to/a2_sensorized.xml --out a2.xml [--no-meshes]
"""
from __future__ import annotations

import argparse
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent

# joint order = robogauge/policy order (FL/FR/RL/RR x hip/thigh/calf)
JOINT_ORDER = [f"{leg}_{j}_joint" for leg in ("FL", "FR", "RL", "RR")
               for j in ("hip", "thigh", "calf")]


def _discover_joints(worldbody: ET.Element) -> list[str]:
    """Return hinge joint names found in the body, in document order."""
    found = []
    for j in worldbody.iter("joint"):
        name = j.get("name")
        jtype = j.get("type", "hinge")
        if name and jtype != "free":
            found.append(name)
    return found


def build(src: Path, out: Path, copy_meshes: bool = True) -> Path:
    tree = ET.parse(src)
    root = tree.getroot()
    assert root.tag == "mujoco", f"{src} is not a mujoco model"

    worldbody = root.find("worldbody")
    assert worldbody is not None, "no <worldbody>"
    base = worldbody.find("./body[@name='base_link']")
    assert base is not None, "robogauge requires a body named 'base_link'"

    # the base_link must carry a freejoint named in a way the sim handles; the sim removes ALL
    # freejoints and adds its own — normalize the locked 'floating_base_joint' free joint to a
    # plain <freejoint> so the sim's `j.tag == 'freejoint'` removal path matches.
    for j in list(base):
        if j.tag == "joint" and j.get("type") == "free":
            base.remove(j)
    fj = ET.Element("freejoint")
    base.insert(0, fj)  # first child of base_link

    joints = _discover_joints(worldbody)
    missing = [j for j in JOINT_ORDER if j not in joints]
    assert not missing, f"body is missing required joints: {missing}"

    # --- meshes: copy STLs into assets/ and rewrite meshdir so the result is self-contained ---
    compiler = root.find("compiler")
    if compiler is None:
        compiler = ET.SubElement(root, "compiler")
    if copy_meshes:
        src_meshdir = Path(compiler.get("meshdir", "."))
        if not src_meshdir.is_absolute():
            src_meshdir = (src.parent / src_meshdir).resolve()
        assets_dir = out.parent / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        for mesh in root.iter("mesh"):
            fn = mesh.get("file")
            if not fn:
                continue
            sp = src_meshdir / fn
            if sp.exists():
                shutil.copy2(sp, assets_dir / Path(fn).name)
        compiler.set("meshdir", "assets")
    else:
        # strip visual meshes (group=2) — keep collision geoms so the robot still has a body
        for asset in root.findall("asset"):
            for mesh in list(asset.findall("mesh")):
                asset.remove(mesh)
        for body in worldbody.iter("body"):
            for geom in list(body.findall("geom")):
                if geom.get("mesh") is not None:
                    body.remove(geom)
        compiler.set("meshdir", ".")

    # --- actuators: 12 position-less motors (robogauge applies its own PD torque) -------------
    # remove any existing actuator block, then synthesize one motor per joint in JOINT_ORDER.
    for a in root.findall("actuator"):
        root.remove(a)
    actuator = ET.SubElement(root, "actuator")
    for jn in JOINT_ORDER:
        m = ET.SubElement(actuator, "motor")
        m.set("name", jn.replace("_joint", ""))  # FL_hip, FL_thigh, ...
        m.set("joint", jn)

    # --- sensors: robogauge's expected set, synthesized from the joint list ------------------
    for s in root.findall("sensor"):
        root.remove(s)
    sensor = ET.SubElement(root, "sensor")
    for jn in JOINT_ORDER:
        ET.SubElement(sensor, "jointpos", {"name": f"{jn}_pos", "joint": jn})
    for jn in JOINT_ORDER:
        ET.SubElement(sensor, "jointvel", {"name": f"{jn}_vel", "joint": jn})
    for jn in JOINT_ORDER:
        ET.SubElement(sensor, "jointactuatorfrc",
                      {"name": f"{jn}_torque", "joint": jn, "noise": "0.01"})
    # IMU on the 'imu' site (present in the sensorized body)
    ET.SubElement(sensor, "framequat", {"name": "imu_quat", "objtype": "site", "objname": "imu"})
    ET.SubElement(sensor, "gyro", {"name": "imu_gyro", "site": "imu"})
    ET.SubElement(sensor, "accelerometer", {"name": "imu_acc", "site": "imu"})
    ET.SubElement(sensor, "framepos", {"name": "frame_pos", "objtype": "site", "objname": "imu"})
    ET.SubElement(sensor, "framelinvel", {"name": "frame_vel", "objtype": "site", "objname": "imu"})

    ET.indent(tree, space="  ")
    out.parent.mkdir(parents=True, exist_ok=True)
    tree.write(out, encoding="unicode", xml_declaration=False)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    default_src = Path("/Users/jibujin/Developer/PerceptionGame/tools/gear_sonic_fk/"
                       "out/a2_sensorized/a2_sensorized.xml")
    ap.add_argument("--src", type=Path, default=default_src,
                    help="locked A2 sensorized MJCF (the body source)")
    ap.add_argument("--out", type=Path, default=HERE / "a2.xml")
    ap.add_argument("--no-meshes", action="store_true",
                    help="strip visual meshes (headless CI where STLs are absent)")
    args = ap.parse_args()
    out = build(args.src, args.out, copy_meshes=not args.no_meshes)
    import mujoco
    m = mujoco.MjModel.from_xml_path(str(out))
    print(f"[make_a2_robot_xml] wrote {out}: nq={m.nq} nv={m.nv} nu={m.nu} nsensor={m.nsensor}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
